### ISSUE TITLE
Use data from pixy to determine position/angle

### ISSUE THREAD

**Issue by Podcakero** [Team2890HawkCollective/Quetzalcoatl#14]
Talk with Douglas to figure out geometry math.
Find out what the getAngle() method does

**Comment by Valance23322** [comment]
What is the status of this issue @Podcakero

**Comment by Podcakero** [comment]
we return the difference in the heights of the two detected blocks to determine how much we should rotate. when the difference equals 0 we then return (((x1-x2)/2) -150) where x1 is the left target, x2 is the right target, and 150 is the middle of the camera video stream. when this equals 0 we return the value of the lidar rangefinder - 100 to set our forwards speed. we stop when this equals 0

**Comment by Podcakero** [comment]
its the arduino code. its all in loop.

**Comment by Podcakero** [comment]
there are commands in java that read in the data sent and do the actions when needed

**Comment by Podcakero** [comment]
i can better explain it to you if you are coming today. ill work on a flowchart/diagram detailing it

**Comment by Valance23322** [comment]
Awaiting PixyCam to be installed on robot

**Comment by Team2890** [comment]
Pixycam is installed on robot
need time to test

**Comment by Podcakero** [comment]
Position and angle have been determined for awhile. This needs testing. #33 takes care of that
