### ISSUE TITLE
Send lidar data to rio

### ISSUE THREAD

**Issue by Podcakero** [Team2890HawkCollective/Quetzalcoatl#15]
https://github.com/adafruit/Adafruit_VL6180X <- Arduino libs. Has all the bits needed to be written to the sensor via I2C
http://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/I2C.html <- Use this to create an I2C object and write the bits

**Comment by Team2890** [comment]
Need to serial communicate with an arduino that has the sensor attached

**Comment by Podcakero** [comment]
Same as issue #18
