### ISSUE TITLE
Write Encoder interface

### ISSUE THREAD

**Issue by Team2890** [Team2890HawkCollective/Quetzalcoatl#2]
Need to have a way to consume the data from the encoders

**Comment by Podcakero** [comment]
Waiting for drivetrain to finish up so we can equate the encoder values to distance

**Comment by Podcakero** [comment]
Drivetrain is finished
We need to switch over the talons to the ones with the encoder (electrical)

**Comment by Valance23322** [comment]
Is the electrical team aware that the talons need to be switched?

**Comment by Team2890** [comment]
Nah
