### ISSUE TITLE
Merge code branches into master

### ISSUE THREAD

**Issue by Valance23322** [Team2890HawkCollective/Quetzalcoatl#24]
Incorporate added functionality into the current control setup when branches are merged

**Comment by Team2890** [comment]
DriveTrainJoystick has been merged into DriveTrain branch

**Comment by Team2890** [comment]
Merged DriveTrain into ArmManipulator

**Comment by Team2890** [comment]
Merged ArmManipulator into GrabberTesting

**Comment by Team2890** [comment]
Merged GrabberTesting into LiftTesting

**Comment by Team2890** [comment]
Merged PixyCam into master

**Comment by Valance23322** [comment]
Deleted a number of merged branches, not sure if it worked, may need to revisit this

**Comment by Team2890** [comment]
Master **SHOULD** be up to date. It has the auton code and drivetrain code.
