### ISSUE TITLE
Program Light for the Camera

### ISSUE THREAD

**Issue by Team2890** [Team2890HawkCollective/Quetzalcoatl#3]

**Comment by Podcakero** [comment]
Slater has this working off of arduino.
We can send commands via rio (IF WE WANT), or we just edit the C code on the arduino

**Comment by Valance23322** [comment]
@Podcakero What is the status of this issue, also you need to update this in the Sprint tracker

**Comment by Podcakero** [comment]
its working properly. the light for the camera turns on and the driverAssist light changes colors
