### ISSUE TITLE
Program Flashy Lights

### ISSUE THREAD

**Issue by Team2890** [Team2890HawkCollective/Quetzalcoatl#4]

**Comment by Podcakero** [comment]
Talk with Slater about the long strands of LEDs he has. May need to code in the same way as the NeoPixel.

**Comment by Podcakero** [comment]
Also done
Mostr likely we will edit the arduino code

**Comment by Valance23322** [comment]
@Podcakero This issue needs to be moved to in-Progress for the sprint

**Comment by Podcakero** [comment]
the ring light does change color properly. we need the lights to be fully mounted on the robot to finalise the code however

**Comment by Podcakero** [comment]
150 leds

**Comment by Podcakero** [comment]
Can't test because lights not ADDED

**Comment by Podcakero** [comment]
Code is created. It works with a ring light. Awaiting testing with the long strand
