### ISSUE TITLE
Configure buttons for autonomous control

### ISSUE THREAD

**Issue by Team2890** [Team2890HawkCollective/Quetzalcoatl#40]

**Comment by Team2890** [comment]
Created [Automated Subsystems.](https://github.com/Team2890HawkCollective/Quetzalcoatl/blob/dfcc57f6d71c227edfe8f1dc63c10261ac3a7006/src/main/java/frc/robot/subsystems/AutomatedSubsytem.java)([commit](https://github.com/Team2890HawkCollective/Quetzalcoatl/commit/dfcc57f6d71c227edfe8f1dc63c10261ac3a7006)) In there, added buttons A, B, and Y to the Assisted Driver's Controller. The buttons move the lift to the height of the different levels. Changed it to an enumerated type called Rocket Level 1, 2, and 3. Implemented javadoc for the method. Added automated subsystems to RobotMap. Implemented xboxAutonomousControl to xboxDriveCommand and joystickDriveCommand.

**Comment by Team2890** [comment]
The buttons to control elevator movement work
Need to test pixy cam

**Comment by Podcakero** [comment]
Buttons are configured
And PixyCam testing is taken care of by #33
