### ISSUE TITLE
RaiseElevatorCommand will always move the elevator up, even if we need to go down

### ISSUE THREAD

**Issue by Podcakero** [Team2890HawkCollective/Quetzalcoatl#48]
Change name to MoveElevatorCommand and have a check to see if the current position if less than or greater than the target, and call elevatorUp or elevatorDown accordingly

**Comment by Team2890** [comment]
Branched from master into new branch ElevatorCommand. Changed name to MoveElevatorCommand and checked whether or not position of encoder was equal to, greater then, or less than the encoder position. elevatorUp and elevatorDown are called accordingly. Needs testing

**Comment by Valance23322** [comment]
Changes have been merged into master, this did not work at last test

**Comment by Team2890** [comment]
Last test this did allow the elevator to move between levels with ease, even from level 3 to level 1
