### ISSUE TITLE
Program Lift mechanism motors

### ISSUE THREAD

**Issue by Team2890** [Team2890HawkCollective/Quetzalcoatl#6]
Assigned to Alex

**Comment by Podcakero** [comment]
NEO Brushless will be used for the Lift
NEO Brushless code is working. 
https://www.revrobotics.com/content/sw/max/sw-docs/java/com/revrobotics/package-summary.html

**Comment by Team2890** [comment]
Wrote code for xbox assistant driver controller to move up and down with triggers.
