### ISSUE TITLE
Program cargo (intake/outtake) mechanism

### ISSUE THREAD

**Issue by Team2890** [Team2890HawkCollective/Quetzalcoatl#8]

**Comment by Podcakero** [comment]
Most probably will be driven by Talons, consisting of AT MOST 3 redline motors, each which needs to be separately controlled. For intake, bottom two are spun up in opposing directions. For outake, front two will be spun up in opposite directions (for a 3 motor system).
For 2 motor: intake - rear motor spun up, front stays stationary. Outake - front motors spins up, rear stays stationary
Motors spin fast, so have a modifier of like... 0.05 (5%) max motor speed.

**Comment by Podcakero** [comment]
Configuration of motors not finalised

**Comment by Podcakero** [comment]
It is decided (currently) that one motor will be used for intake/outake
And a servo at the top for keeping the ball in/letting it out
See: Ty/Slater

**Comment by Valance23322** [comment]
Servo is being re-purposed to control the hatches.  Blocked while waiting on hardware implementation.

**Comment by Podcakero** [comment]
we are awaiting finalisation of cad and the prototype to be finished

**Comment by Valance23322** [comment]
Preliminary code has been written, currently awaiting hardware fixes so code can be tested.

**Comment by Valance23322** [comment]
Code has been tested and correctly spins the motors, however the mechanism does not pick up the ball.  Team is currently attempting hardware modification to resolve issue.

**Comment by Team2890** [comment]
Mechanism picks up and shoots balls.
can pick up from bottom and front
